name: Publish Image to Docker Hub

# GHA workflows for "run this only after a PR merge to master" are weird, still hacking here
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      # GHA workflows for "run this only after a PR merge to master" are weird, still hacking here
      if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: covital/ingress
        # adds an additional unique 202003251103shagoeshere tag
        snapshot: true
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
