name: Publish Image to Docker Hub

# only run after PRs merge to master
#   from https://github.community/t5/GitHub-Actions/Trigger-workflow-only-on-pull-request-MERGE/td-p/43201
if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: covital/ingress
        # adds an additional unique 202003251103shagoeshere tag
        snapshot: true
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
