name: Publish Image to Docker Hub

on:
  # run after each push to master, including PR merges
  # will not run proactively on pre-merge master PRs!
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: covital/ingress
        # adds an additional unique 202003251103shagoeshere tag
        snapshot: true
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
